---
apiVersion: source.toolkit.fluxcd.io/v1beta1
kind: GitRepository
metadata:
  name: fj
  namespace: flux-system
spec:
  interval: 30s
  ref:
    branch: main
  url: https://github.com/alibadrzain/fj-infra
