---
apiVersion: source.toolkit.fluxcd.io/v1beta1
kind: GitRepository
metadata:
  name: fj
  namespace: flux-system
spec:
  interval: 30s
  ref:
    branch: master
  url: https://github.com/alibadrzain/fj

flux create kustomization fj \
  --source=fj \
  --path="./kustomize" \
  --prune=true \
  --validation=client \
  --interval=5m \
  --export > ./clusters/staging/fj-kustomization.yaml